# Generated by Django 5.2.1 on 2025-05-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_cv', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='generated_pdfs/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('stack', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
